# Generated by Django 2.0.7 on 2018-07-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=20, unique=True)),
                ('userPasswd', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=12)),
                ('nickName', models.CharField(default='', max_length=50, verbose_name='昵称')),
                ('imgPath', models.ImageField(max_length=500, upload_to='static/uploads')),
                ('state', models.BooleanField(default=True, verbose_name='用户状态')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'weomen_user',
            },
        ),
    ]
