# Generated by Django 2.0.7 on 2018-07-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nickName',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='imgPath',
            field=models.ImageField(default='', max_length=500, null=True, upload_to='static/uploads'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', max_length=12, null=True),
        ),
    ]
