# Generated by Django 2.0.7 on 2018-07-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20180718_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='swImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'weomen_swImg',
            },
        ),
    ]
