# Generated by Django 2.0.7 on 2018-07-19 15:46

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_swimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(default='')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='内容')),
                ('Ename', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=50)),
                ('introduce', models.CharField(max_length=200)),
                ('cnt', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.User')),
            ],
            options={
                'db_table': 'weomen_content',
            },
        ),
    ]
