# Generated by Django 2.0.7 on 2018-07-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='summary',
        ),
        migrations.AddField(
            model_name='content',
            name='images',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='Ename',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='Name',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='cnt',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='content',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='introduce',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
