# Generated by Django 2.0.7 on 2018-07-20 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_auto_20180719_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='Ename',
        ),
        migrations.RemoveField(
            model_name='content',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='content',
            name='introduce',
        ),
    ]
